name: Deploy index.html to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy index.html to server via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: devuser
          key: ${{ secrets.SSH_KEY }}
          source: "index.html"
          target: "/var/www/html/index.html"
