name: Автосборка проекта

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v4

      - name: Показать список файлов
        run: ls -la

      - name: Показать содержимое index.html
        run: cat index.html
